services:
  app:
    build: ./blog-api
    container_name: blog_api
    ports:
      - "8289:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=blog_db
      - REDIS_HOST=redis
      - JWT_SECRET=supersecretkey
    networks:
      - blog-app-network

  mysql:
    image: mysql:8.0
    container_name: blog_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_db
    ports:
      - "3329:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blog-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: blog_redis
    ports:
      - "6489:6379"
    networks:
      - blog-app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis-insight:
    image: redis/redisinsight:latest
    container_name: blog_redis_insight
    restart: always
    ports:
      - "8298:8001"
    networks:
      - blog-app-network
    depends_on:
      - redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: blog_redis_commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8299:8081"
    networks:
      - blog-app-network
    depends_on:
      - redis

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: blog_phpmyadmin
    restart: always
    ports:
      - "8288:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - blog-app-network

networks:
  blog-app-network:

volumes:
  mysql_data: